### ISSUE TITLE
Error in array_map?

### ISSUE THREAD

**Issue by mylittleshorint** [tentwentyfour/remaim#20]
I'm stuck with an errr in array_map.

I printed out in Wizard.php using

```
        return array_map(function ($issue) use ($ph_project, $policies, $resume) {
            echo 'details: ';
            print_r( $details = $this->redmine->getIssueDetail($issue['id']));
            echo 'owner: ';
            print_r( $owner = $this->grabOwnerPhid($details['issue']));

```

bitnami@phab:~/apps/remaim$ php bin/remaim

Attempting to connect to good ol' Redmine... success!
Stand by while we are retrieving a list of projects from your Redmine instance...
15 total projects retrieved.

[1 – Devel]
[4 – Spielwiese]

Please select (type) a project ID
> 4
Found project "Spielwiese" on your Redmine instance.

Now you've got to decide where to put all that stuff... decisions, decisions!
Please enter the id or slug of the project in Phabricator if you know it
or press
        [Enter] to see a list of available projects in Phabricator,
        [0] to create a new project from the Redmine project's details or
        [q] to quit and abort
> 3
Found project "Spielwiese" with PHID PHID-PROJ-72abjdgc6a7rk72xvoui

Let's set some policies on the new tasks, shall we?
Here are the group projects that I found:

Select a group to get view and edit permissions
>
You must select a value between 0 and 0
Select a group to get view and edit permissions
> 0
PHP Notice:  Undefined offset: 0 in /opt/bitnami/apps/remaim/src/Wizard.php on line 339

####################
# Pre-flight check #
####################
Redmine project named "Spielwiese" with ID 4.
Target phabricator project named "Spielwiese" with ID 3.
View policy: , Edit policy:
1 tickets to be migrated!

OK to continue? [y/N]
> y
Working...
details: Array
(
    [issue] => Array
        (
            [id] => 3352
            [project] => Array
                (
                    [id] => 4
                    [name] => Spielwiese
                )

            [tracker] => Array
                (
                    [id] => 5
                    [name] => Default
                )

            [status] => Array
                (
                    [id] => 1
                    [name] => Open
                )

            [priority] => Array
                (
                    [id] => 5
                    [name] => High
                )

            [author] => Array
                (
                    [id] => 59
                    [name] => ShorInt
                )

            [assigned_to] => Array
                (
                    [id] => 59
                    [name] => ShorInt
                )

            [category] => Array
                (
                    [id] => 72
                    [name] => Miscellaneous
                )

            [subject] => MyTestSub
            [description] => MyTestDescription
            [done_ratio] => 0
            [custom_fields] => Array
                (
                    [0] => Array
                        (
                            [id] => 3
                            [name] => MY ID
                            [multiple] => 1
                            [value] => Array
                                (
                                    [0] => 2 (EG)
                                )

                        )

                )

            [created_on] => 2017-02-10T10:23:31Z
            [updated_on] => 2017-02-10T10:30:32Z
            [attachments] => Array
                (
                )

            [journals] => Array
                (
                    [0] => Array
                        (
                            [id] => 19830
                            [user] => Array
                                (
                                    [id] => 59
                                    [name] => ShorInt
                                )

                            [notes] =>
                            [created_on] => 2017-02-10T10:30:32Z
                            [details] => Array
                                (
                                    [0] => Array
                                        (
                                            [property] => attr
                                            [name] => priority_id
                                            [old_value] => 7
                                            [new_value] => 5
                                        )

                                )

                        )

                )

            [watchers] => Array
                (
                )

        )

)
owner: Array
(
)
Migrating issue 3352 - "MyTestSub"...
**PHP Warning:  array_map(): An error occurred while invoking the map callback in /opt/bitnami/apps/remaim/src/Wizard.php on line 444**
Arrrgh… we're really sorry but something went a little haywire here.
Use the following information to help us fix it? Pretty please?

Exception message: ERR-CONDUIT-CORE: Exception when processing transaction of type "view".
Exception trace:
#0 /usr/share/libphutil/src/future/FutureProxy.php(58): ConduitFuture->didReceiveResult(Array)
#1 /usr/share/libphutil/src/future/FutureProxy.php(35): FutureProxy->getResult()
#2 /usr/share/libphutil/src/conduit/ConduitClient.php(64): FutureProxy->resolve()
#3 /opt/bitnami/apps/remaim/src/Traits/Phabricator.php(257): ConduitClient->callMethodSynchronous('maniphest.edit', Array)
#4 /opt/bitnami/apps/remaim/src/Wizard.php(493): Ttf\Remaim\Wizard->createOrUpdatePhabTicket(Array, Array)
#5 /opt/bitnami/apps/remaim/src/Wizard.php(443): Ttf\Remaim\Wizard->createManiphestTask(Array, Array, 'PHID-PROJ-72abj...', Array, false)
#6 [internal function]: Ttf\Remaim\Wizard->Ttf\Remaim\{closure}(Array)
#7 /opt/bitnami/apps/remaim/src/Wizard.php(444): array_map(Object(Closure), Array)
#8 /opt/bitnami/apps/remaim/src/Wizard.php(139): Ttf\Remaim\Wizard->migrateIssues(Array, Array, Array, false)
#9 /opt/bitnami/apps/remaim/bin/remaim(84): Ttf\Remaim\Wizard->run(false)
#10 {main}
```

**Comment by kwisatz** [comment]
Hi @mylittleshorint thanks for reporting this.

Can you please supply the following information:
- the branch or version of remaim you're using
- Whether your user's real names in Phabricator are the same as those in Redmine? 
- Do you have a "project" of type "group" defined in Phabricator? Looks like there's a problem with setting ownership/policies on the tasks/projects.

**Comment by mylittleshorint** [comment]
Hi @kwisatz thanks for your answer. Adding a "project" of type "group" solved it

**Comment by kwisatz** [comment]
I'm happy to hear that.
I'm going to re-open the issue since I believe we should have some kind of warning/error in place if this is missing on the destination phabricator instance.
