### ISSUE TITLE
Error with new tasks policies?

### ISSUE THREAD

**Issue by ghost** [tentwentyfour/remaim#26]
I'm trying to make a migration. Remaim perfectly sees the projects of both Redmine and Phabricator. But when you try to select a policy, it produces an empty list.
```
Let's set some policies on the new tasks, shall we?
Here are the group projects that I found:

Select a group to give view and edit permissions to
> 
You must select a value between 0 and 0
Select a group to give view and edit permissions to
> 0
```

I do not know what should be there, as soon as I start to deal with Phabricator and in its settings I do not find anything like it. If I select 0, then when I start the migration, I get this error:

```
PHP Notice:  Undefined offset: 0 in /var/www/phab/convert/remaim/src/Wizard.php on line 345
Arrrgh… we're really sorry but something went a little haywire here.
Use the following information to help us fix it? Pretty please?

Exception message: ERR-CONDUIT-CORE: Exception when processing transaction of type "view": Error while reading "value": Expected string, got something else.
Exception trace:
#0 /var/www/phab/libphutil/src/future/FutureProxy.php(58): ConduitFuture->didReceiveResult(Array)
#1 /var/www/phab/libphutil/src/future/FutureProxy.php(35): FutureProxy->getResult()
#2 /var/www/phab/libphutil/src/conduit/ConduitClient.php(64): FutureProxy->resolve()
#3 /var/www/phab/convert/remaim/src/Traits/Phabricator.php(156): ConduitClient->callMethodSynchronous('project.edit', Array)
#4 /var/www/phab/convert/remaim/src/Wizard.php(272): Ttf\Remaim\Wizard->createNewPhabricatorProject(Array, Array, Array)
#5 /var/www/phab/convert/remaim/src/Traits/Phabricator.php(118): Ttf\Remaim\Wizard->actOnChoice('0', '1')
#6 /var/www/phab/convert/remaim/src/Wizard.php(128): Ttf\Remaim\Wizard->selectOrCreatePhabricatorProject('1')
#7 /var/www/phab/convert/remaim/bin/remaim(102): Ttf\Remaim\Wizard->run(false)
#8 {main}
```

**Comment by BugHunter2k** [comment]
As I stumbled above this same problem, here is how to solve:
There are no real groups in Phabricator, instead u can create a project to use for grouping your users. 
See here: https://stackoverflow.com/a/42106647
